sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t udeshyagiri/classroom-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true udeshyagiri/classroom-client npm run test

after_success:
  - docker build -t udeshyagiri/classroom-client ./client
  - docker build -t udeshyagiri/classroom-auth ./auth
  - docker build -t udeshyagiri/classroom-students ./students
  - docker build -t udeshyagiri/classroom-teachers ./teachers
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push udeshyagiri/classroom-client
  - docker push udeshyagiri/classroom-auth
  - docker push udeshyagiri/classroom-students
  - docker push udeshyagiri/classroom-teachers
